language: ruby
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails_4.0_pc_4_1.gemfile
  - gemfiles/rails_4.0_pc_4_2.gemfile
  - gemfiles/rails_4.2_pc_4_1.gemfile
  - gemfiles/rails_4.2_pc_4_2.gemfile
