language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
env:
  - PAPERCLIP_VERSION=
  - PAPERCLIP_VERSION="2.5.2"
  - PAPERCLIP_VERSION="~> 2.8"
script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
